repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0 , 5 Oct 2024
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=100']
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: '\.(diff|patch)$'
    - id: trailing-whitespace
      exclude: '\.(diff|patch)$'

  # C++ formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 7ec07eeb4135dc6ecf410d24ac4ead986a5d413d # v20.1.3, 28 Apr 2025
    hooks:
    - id: clang-format
      types_or: [file]
      files: \.(cc|hh|h|cpp|hpp|cu|cuh)$

ci:
  autoupdate_schedule: quarterly
  autoupdate_commit_msg: "Update pre-commit version"

# vim: set nowrap tw=100:
