; Measurements
declare %Result* @__quantum__qis__m__body(%Qubit*)
declare %Result* @__quantum__qis__measure__body(%Array*, %Array*)
declare %Result* @__quantum__qis__mresetz__body(%Qubit*)
declare void @__quantum__qis__mz__body(%Qubit*, %Result*)
declare qstate @__quantum__qis__read_result__body(%Result*)

; Gates
declare void @__quantum__qis__ccx__body(%Qubit*, %Qubit*)
declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)
declare void @__quantum__qis__cx__body(%Qubit*, %Qubit*)
declare void @__quantum__qis__cy__body(%Qubit*, %Qubit*)
declare void @__quantum__qis__cz__body(%Qubit*, %Qubit*)
declare void @__quantum__qis__exp__adj(%Array*, double, %Array*)
declare void @__quantum__qis__exp__body(%Array*, double, %Array*)
declare void @__quantum__qis__exp__ctl(%Array*, %Tuple*)
declare void @__quantum__qis__exp__ctladj(%Array*, %Tuple*)
declare void @__quantum__qis__h__body(%Qubit*)
declare void @__quantum__qis__h__ctl(%Array*, %Qubit*)
declare void @__quantum__qis__r__adj(i2, double, %Qubit*)
declare void @__quantum__qis__r__body(i2, double, %Qubit*)
declare void @__quantum__qis__r__ctl(%Array*, %Tuple*)
declare void @__quantum__qis__r__ctladj(%Array*, %Tuple*)
declare void @__quantum__qis__reset__body(%Qubit*)
declare void @__quantum__qis__rx__body(double, %Qubit*)
declare void @__quantum__qis__rx__ctl(%Array*, %Tuple*)
declare void @__quantum__qis__rxx__body(double, %Qubit*, %Qubit*)
declare void @__quantum__qis__ry__body(double, %Qubit*)
declare void @__quantum__qis__ry__ctl(%Array*, %Tuple*)
declare void @__quantum__qis__ryy__body(double, %Qubit*, %Qubit*)
declare void @__quantum__qis__rz__body(double, %Qubit*)
declare void @__quantum__qis__rz__ctl(%Array*, %Tuple*)
declare void @__quantum__qis__rzz__body(double, %Qubit*, %Qubit*)
declare void @__quantum__qis__s__adj(%Qubit*)
declare void @__quantum__qis__s__body(%Qubit*)
declare void @__quantum__qis__s__ctl(%Array*, %Qubit*)
declare void @__quantum__qis__s__ctladj(%Array*, %Qubit*)
declare void @__quantum__qis__swap__body(%Qubit*, %Qubit*)
declare void @__quantum__qis__t__adj(%Qubit*)
declare void @__quantum__qis__t__body(%Qubit*)
declare void @__quantum__qis__t__ctl(%Array*, %Qubit*)
declare void @__quantum__qis__t__ctladj(%Array*, %Qubit*)
declare void @__quantum__qis__x__body(%Qubit*)
declare void @__quantum__qis__x__ctl(%Array*, %Qubit*)
declare void @__quantum__qis__y__body(%Qubit*)
declare void @__quantum__qis__y__ctl(%Array*, %Qubit*)
declare void @__quantum__qis__z__body(%Qubit*)
declare void @__quantum__qis__z__ctl(%Array*, %Qubit*)

; Assertions
declare void @__quantum__qis__assertmeasurementprobability__body(%Array*, %Array*, %Result*, double, %String*, double)
declare void @__quantum__qis__assertmeasurementprobability__ctl(%Array*, %Tuple*)
